sudo: required
language: bash
services:
  - docker

before_install:
  #Setup test directory on travis
  - sudo chmod -R 777 $HOME
  - TEST_DIR_TRAVIS=$HOME/test_dir
  - mkdir $TEST_DIR_TRAVIS
  - cp -r $TRAVIS_BUILD_DIR $TEST_DIR_TRAVIS/candidate
  - git clone git@github.com:NCAR/wrf_hydro_nwm.git $TEST_DIR_TRAVIS/reference
  - sudo chmod -R 777 $TEST_DIR_TRAVIS
  #Get docker images
  - docker pull wrfhydro/dev:conda
  - docker pull wrfhydro/domains:croton_lite
  - docker create --name croton_lite wrfhydro/domains:croton_lite
  #Setup test directory on Docker
  - TEST_DIR_DOCKER=/home/docker/test_dir
  - PYTEST_DIR_DOCKER=$TEST_DIR_DOCKER/candidate/tests
  - DOMAIN_DIR_DOCKER=/home/docker/domain/croton_lite

script:
  - docker run --volumes-from croton_lite -v $TEST_DIR_TRAVIS:$TEST_DIR_DOCKER wrfhydro/dev:conda /bin/bash -c "pip install wrfhydro; pytest $PYTEST_DIR_DOCKER -v --domain_dir $DOMAIN_DIR_DOCKER --candidate_dir $TEST_DIR_DOCKER/candidate/trunk/NDHMS --reference_dir $TEST_DIR_DOCKER/reference/trunk/NDHMS --output_dir $TEST_DIR_DOCKER/test_out"
