sudo: required
language: bash
services:
  - docker

before_install:
  #Setup test directory on travis
  - TEST_DIR_TRAVIS=$HOME/test_dir
  - sudo mkdir $TEST_DIR_TRAVIS
  - sudo chmod -R 777 $TEST_DIR_TRAVIS
  - cp -r $TRAVIS_BUILD_DIR $TEST_DIR_TRAVIS/candidate
  - git clone https://github.com/NCAR/wrf_hydro_nwm_public.git $TEST_DIR_TRAVIS/reference
  - cd $TEST_DIR_TRAVIS/reference
  - git checkout $TRAVIS_BRANCH
  - sudo chmod -R 777 $TEST_DIR_TRAVIS
  #Get docker images
  - docker pull wrfhydro/dev:conda
  #Get domain from latest release
  - DOMAIN_DIR_TRAVIS=$HOME/example_case
  - release=$(curl -s https://api.github.com/repos/NCAR/wrf_hydro_nwm_public/releases/latest)
  - exampleCaseURL=$(echo "$release" | grep 'testcase' | grep "browser_download_url" | cut -d ':' f2,3 |  tr -d \")
  - echo $exampleCaseURL
  - echo "$exampleCaseURL" | wget -qi -
  - tar -xf *testcase*.tar.gz -C $HOME
  - sudo chmod -R 777 $DOMAIN_DIR_TRAVIS
  #Setup test directory on Docker
  - TEST_DIR_DOCKER=/home/docker/test_dir
  - PYTEST_DIR_DOCKER=$TEST_DIR_DOCKER/candidate/tests
  - DOMAIN_DIR_DOCKER=/home/docker/domain/example_case

script:
  - docker run -v $DOMAIN_DIR_TRAVIS:$DOMAIN_DIR_DOCKER -v $TEST_DIR_TRAVIS:$TEST_DIR_DOCKER wrfhydro/dev:conda /bin/bash -c "pip uninstall -y wrfhydropy; pip install wrfhydropy==0.0.5.dev0; cd $PYTEST_DIR_DOCKER; pytest -v --ignore local --ignore toolbox/ --config nwm_ana --compiler gfort --domain_dir $DOMAIN_DIR_DOCKER --candidate_dir $TEST_DIR_DOCKER/candidate/trunk/NDHMS --reference_dir $TEST_DIR_DOCKER/reference/trunk/NDHMS --output_dir $TEST_DIR_DOCKER/test_out"

