version: 2
jobs:
  build:
    docker:
      - image: wrfhydro/ci:sixmile     
#        auth:
#          username: $DOCKER_USERNAME  
#          password: $DOCKER_PASSWORD
    working_directory: /home/docker
    steps:
      - run:
          name: Clone testing repo
          command: git clone https://${GITHUB_USERNAME}:${GITHUB_AUTHTOKEN}@github.com/NCAR/wrf_hydro_tests /home/docker/wrf_hydro_tests
      - run:
          name: Configure environment
          command: cd /home/docker/wrf_hydro_tests/CI; source bash_env_setup.sh; cd -
      - checkout:
          path: /home/docker/repos/candidate
      - run:
          name: Compile ?
          command: bash /home/docker/wrf_hydro_tests/questions/compile.sh
      - run:
          name: Run ?
          command: bash /home/docker//wrf_hydro_tests/questions/run.sh
      - run:
          name: Restart ?
          command: bash /home/docker//wrf_hydro_tests/questions/perfect_restart.sh
      - run:
          name: Number of cores ?
          command: bash /home/docker/wrf_hydro_tests/questions/number_of_cores.sh
      - run:
          name: Regression ?
          command: bash /home/docker/wrf_hydro_tests/questions/regression.sh
