version: 2
jobs:
  build:
    docker:
      - image: wrfhydro/ci:sixmile     
        auth:
          username: $DOCKER_USERNAME  
          password: $DOCKER_PASSWORD
    working_directory: /wrf_hydro_ci
    steps:
      - run:
          name: Clone testing repo
          command: mkdir /wrf_hydro_ci/temp; git clone https://${GITHUB_USERNAME}:${GITHUB_AUTHTOKEN}@github.com/NCAR/wrf_hydro_ci /wrf_hydro_ci/temp; mv /wrf_hydro_ci/temp/* .; rm -rf temp
      - run:
          name: Configure environment
          command: ./config.sh
      - checkout:
          path: /wrf_hydro_ci/repos/test
      - run:
          name: Compile test
          command: bash runTests.sh compile
      - run:
          name: Regression test
          command: bash runTests.sh run
      - run:
          name: Restart test
          command: bash runTests.sh restart
      - run:
          name: Num cores test
          command: bash runTests.sh ncores

          